baseURL = "https://placidmoon1.github.io"
languageCode = "en-us"
title = "GuHong Min"
theme = "archie"
copyright = "© Gu Hong"
paginate=10 # articles per page


# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/placidmoon1"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4